In [1]:
import investpy as ip

#取得某一國家所有股票資訊                                                 
stocks_df = ip.get_stocks(country='china')

#取得各國股票歷史資料
df = ip.get_stock_historical_data(stock='AAPL',
                                        country='United States',
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')
#取得各國基金歷史資料
df = ip.get_fund_historical_data(fund='bbva plan multiactivo moderado pp',
                                       country='spain',
                                       from_date='01/01/2010',
                                       to_date='01/01/2019')
#取得ETF歷史資料
df = ip.get_etf_historical_data(etf='bbva accion dj eurostoxx 50',
                                      country='spain',
                                      from_date='01/01/2018',
                                      to_date='01/01/2019')
#取得匯率資訊
df = ip.get_currency_cross_historical_data(currency_cross='EUR/USD',
                                                 from_date='01/01/2018',
                                                 to_date='01/01/2019')
                                                 
#取得基金資訊
fund_information = ip.get_fund_information(fund='bbva plan multiactivo moderado pp',
                                                 country='spain',
                                                 as_json=True)
#取得某一國家所有股票資訊                                                 
stocks_df = ip.get_stocks(country='china')

#取得單一公司的簡介
ip.get_stock_company_profile(stock='bbva', country='spain', language='english')

In [10]:
ip.get_stock_company_profile(stock='1101', country='taiwan', language='chinese') #沒有中文語系的資料
stocks = ip.get_stocks(country='taiwan')

ValueError: ERR#0014: the specified language is not valid, it can just be either spanish (es) or english (en).

In [13]:
df = ip.get_stock_historical_data(stock='3105',
                                        country='taiwan',
                                        from_date='01/01/2010',
                                        to_date='01/01/2020')

             Open   High    Low  Close   Volume Currency
Date
2017-03-02  124.5  125.0  118.5  123.5  6273000      TWD
2017-03-03  122.5  125.5  121.5  125.0  4423000      TWD
2017-03-06  124.5  124.5  121.5  123.5  2471000      TWD
2017-03-07  123.5  131.0  123.0  129.5  7660000      TWD
2017-03-08  128.0  128.5  125.5  127.5  3629000      TWD
...           ...    ...    ...    ...      ...      ...
2019-12-25  294.0  296.5  291.0  295.0  3554000      TWD
2019-12-26  297.0  301.5  293.5  300.0  7118000      TWD
2019-12-27  303.0  308.0  298.5  298.5  8976000      TWD
2019-12-30  300.5  302.0  296.5  297.5  4812000      TWD
2019-12-31  297.5  299.5  293.0  294.0  4495000      TWD

[700 rows x 6 columns]